[build]
  base = "/"
  publish = "frontend/dist"
  command = "./netlify-build.sh"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[[plugins]]
  package = "@netlify/plugin-functions-install-core" 